task: train

defaults:
  - validation: ../validation

epoch: 100

data:
  batch_size: 32
  image_size: ${image_size}
  cpu_num: ${cpu_num}
  shuffle: True
  pin_memory: True
  data_augment:
    RandomCrop: 0.05

optimizer:
  type: AdamW
  args:
    lr: 0.001
    weight_decay: 0.0005

loss:
  objective:
    BCELoss: 2.0
    BoxLoss: 4.0
    DFLoss: 1.5
  aux:
    0.25
  matcher:
    iou: CIoU
    topk: 10
    factor:
      iou: 6.0
      cls: 0.5

scheduler:
  type: CosineAnnealingLR
  warmup:
    epochs: 3.0
  args:
    T_max: ${task.epoch}
    eta_min: 0.00001

ema:
  enable: true
  decay: 0.9999
