path: FDI_ordered_labels
train: train
validation: valid

class_num: 32
class_list: ['T11', 'T12', 'T13', 'T14', 'T15', 'T16', 'T17', 'T18', 'T21', 'T22', 'T23', 'T24', 'T25', 'T26', 'T27', 'T28', 'T31', 'T32', 'T33', 'T34', 'T35', 'T36', 'T37', 'T38', 'T41', 'T42', 'T43', 'T44', 'T45',  'T46', 'T47', 'T48']
